<?php

return [

    'Home'=>'Главная страница',
    'Logout'=>'Выход',
    'Login'=>'Вход',
    'ID'=>'ИД',
    'Username'=>'Имя пользователя',
    'Password'=>'пароль',
    'Incorrect username or password.'=>'Неверное имя пользователя или пароль',
    'The requested page does not exist'=>'Запрошенной страницы не существует',
    'Collaborative Learning Game'=>'Совместная обучающая игра',
    'Please fill out the following fields to login:'=>'Пожалуйста заполните следующие поля для входа',
    'Remember Me'=>'Запомнить',
    'Signup'=>'Зарегистрироваться',
    'Students'=>'Студенты',
    'Equations'=>'Уравнение',
    'Inequalities'=>'Неравенства',
    'Functions'=>'Функции',
    'Linear Equations'=>'Линейное Уравнение',
    'Polynomial'=>'Многочлены',
    'Quadratic Equations'=>'Квадратное Уравнение',
    'Statistics'=>'Статистика',
    'Choose Session'=>'Выберите Сеанс',
    'Session' => 'Сеанс',
    'Sessions' => 'Сеансы',
    'Create Session'=> 'Создать сеанс',
    'Teacher' => 'Учитель',
    'Session ID' => 'ИД сеанса',
    'Create Student'=>'Создать студента',
    'Save' => 'Сохранить',
    'Delete' => 'Удалить',
    'Update Session: '=>'Изменить данные сеансa',
    'Token'=>'Код',
    'Name' => 'Имя',
    'Admin ID'=>'ИД Администратора',
    'Search' =>'Искать',
    'Reset'=>'Обратно',
    'Update'=>'Изменить',
    'Update Student: '=>'Изменить данные студента',


];